# Generated by Django 2.1.7 on 2019-08-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyfly', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skyflyrequest',
            name='start',
        ),
        migrations.AddField(
            model_name='skyflyrequest',
            name='length_combinations',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of different date-destination combinations'),
            preserve_default=False,
        ),
    ]
