# Generated by Django 2.1.7 on 2019-05-19 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skyfly', '0002_auto_20190514_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='KiwiException',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('exception_message', models.TextField()),
                ('data', models.TextField()),
                ('skyfly_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='skyfly.SkyflyRequest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
