# Generated by Django 2.1.7 on 2019-05-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyfly', '0003_kiwiexception'),
    ]

    operations = [
        migrations.AddField(
            model_name='skyflyrequest',
            name='completed',
            field=models.DateTimeField(null=True),
        ),
    ]
