# Generated by Django 2.1.7 on 2019-05-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyfly', '0004_skyflyrequest_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kiwiresponse',
            name='deep_link',
            field=models.URLField(max_length=2083),
        ),
    ]
