# Generated by Django 2.1.7 on 2019-05-31 20:50

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('skyfly', '0005_auto_20190529_0701'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='kiwiresponse',
            managers=[
                ('flights', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='skyflyrequest',
            name='start',
            field=models.CharField(default='MUC', max_length=3),
        ),
    ]
