# Generated by Django 2.1.7 on 2019-06-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyfly', '0006_auto_20190531_2050'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='kiwiresponse',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='skyflyrequest',
            name='completed',
        ),
        migrations.AddField(
            model_name='kiwiexception',
            name='traceback',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skyflyrequest',
            name='left_combinations',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of different date-destination combinations left to query'),
            preserve_default=False,
        ),
    ]
