# Generated by Django 2.1.7 on 2019-09-15 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('frontpage', '0002_auto_20190320_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('is_public', models.BooleanField(default=True)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('groups', models.ManyToManyField(blank=True, help_text='Groups that have additional permissions on instances of this model', to='auth.Group', verbose_name='Groups')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('name', models.CharField(max_length=100, verbose_name='Project name')),
                ('is_public', models.BooleanField(default=True)),
                ('logo', filebrowser.fields.FileBrowseField(max_length=200, verbose_name='Image')),
                ('url', models.URLField(verbose_name='Project detail URL')),
                ('groups', models.ManyToManyField(blank=True, help_text='Groups that have additional permissions on instances of this model', to='auth.Group', verbose_name='Groups')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Project Leader')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='post',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontpage.Project', verbose_name='Project'),
        ),
    ]
